### ISSUE TITLE
PPZ Gimmick and Entrance for Galacnik

### ISSUE THREAD

**Issue by DrEggyniks91** [overbound/SonicTimeTwisted2.0#15]
During Act 1 and 2, Galacnik will ramdomly appear in the bg as a distorted, shadowy figure, trying to ramdomly attack the player by either shooting lasers, boulders or even his signature ball projectile. He could also send portals that would bring him back 10 sec. ago.

Also, before starting the boss fight of Galacnik, instead of the platforms getting destroyed, I suggest that after Metal tells something, make his hand grab on to Metal Sonic, throws him away, his hands then grab on the platform and then gets up, as the screen also shakes.

**Comment by overbound** [comment]
We do a lot of these things. And having Galactnik grab metal sonic interferes with my artistic vision.
