### ISSUE TITLE
Arena and additional stuff for AAZ Boss 

### ISSUE THREAD

**Issue by DrEggyniks91** [overbound/SonicTimeTwisted2.0#27]
When introducing the boss, the Mole must have this animation where he's tweaking the Egg Spider, when Sonic meets him, the Mole enter the boss.

Future Arena must be a theatre or on top of a skyscraper.

Past Arena must be on the ground

If in the future, moles in jetpacks will throw bombs. The Egg Spider's laser beam will randomly shoot to the sky and send out rain of lasers (which an icon will tell the location of the laser drop)

In the past, the same attack in the future will happen.

Bombs can send out a wave of fire.

That's all

**Comment by overbound** [comment]
Hilarious but too much of a change.
