### ISSUE TITLE
Parity: Characters are unlockable on Windows, everyone unlocked at start on Android

### ISSUE THREAD

**Issue by IdaDood** [overbound/SonicTimeTwisted2.0#29]
Note: these are the only two platforms I've actually played the game on, so I have no idea if this happens on other systems.
In Windows version 1.1.2, only Sonic is available from the start. Tails and Knuckles have to be unlocked separately.
In Android version 1.1.2, all three are available from the start, with no requirements to get them.
This is kinda minor, but it could be a bit confusing (and already has been.) Could make them all available from the start on all platforms, or make them unlockable on android.

**Comment by BlueSpeedsterYT** [comment]
that looks to be more of a bug than anything.
while it could be fixable (especially with how the other playable characters were playable in the initial release) it really depends on if someone is willing to fix it for both this _and_ 1.1.3

**Comment by overbound** [comment]
There is simply no code to make Tails and Knuckles unlockable so I find this hard to believe.
