### ISSUE TITLE
Tails Doll and Metal Knuckles

### ISSUE THREAD

**Issue by KrabbyCurse** [overbound/SonicTimeTwisted2.0#38]
I want Tails Doll and Metal Knuckles as a Boss Characters

![Tailsdollsuperstars](https://github.com/overbound/SonicTimeTwisted2.0/assets/141451277/3a4cb67d-0442-416b-9b92-ca16bab75f7f)
![Metal_Knuckles_model_Sonic_Superstars_SW](https://github.com/overbound/SonicTimeTwisted2.0/assets/141451277/860c6fba-2cab-4dea-a9ce-8ddf6fd7c5b5)

**Comment by DrEggyniks91** [comment]
Hmm, it would look better if they appear as artifacts or like in repair and then show themselves as a boss.

**Comment by overbound** [comment]
We've documented this in the metro mile boss story.
