### ISSUE TITLE
Metal Amy

### ISSUE THREAD

**Issue by KrabbyCurse** [overbound/SonicTimeTwisted2.0#40]
I want Metal Amy as a Boss Character

![image](https://github.com/overbound/SonicTimeTwisted2.0/assets/141451277/88be3cff-5a87-42d1-90d8-67809774279d)

**Comment by overbound** [comment]
If you really want this please add it as a comment on your Metal Knuckles and Tails Doll request. Not saying it will get done for sure. But it will be considered at least.
