### ISSUE TITLE
Sonia the Hedgehog and Manic the Hedgehog

### ISSUE THREAD

**Issue by UltramanTime** [overbound/SonicTimeTwisted2.0#52]
I want Sonia and Manic to be in Sonic Time Twisted
Because they are siblings

**Comment by overbound** [comment]
Yeah I just don't think characters from the TV shows are going to make it in. Their too low on the list for their effort. Amy, Mighty, Shadow, Metal Sonic, Vector, etc. These are more likely candidates to get added for fun.
