### ISSUE TITLE
Wall Jump

### ISSUE THREAD

**Issue by KrabbyCurse** [overbound/SonicTimeTwisted2.0#54]
My Idea:
Wall Jump for Sonic

https://sonic.fandom.com/wiki/Wall_Jump

**Comment by DrEggyniks91** [comment]
Although it's a good idea, it's never and an unnecessary ability. Most of the levels consists of running and springage. Maybe a wall jump isn't a good idea.

**Comment by overbound** [comment]
This would probably negatively impact the air curling. Sorry! :(
