### ISSUE TITLE
Rocket Shoes and Pogo Spring

### ISSUE THREAD

**Issue by KrabbyCurse** [overbound/SonicTimeTwisted2.0#60]
Idea
I want Rocket Shoes and Pogo Spring to be in Sonic Time Twisted as an Item Boxes
![Sonic-Chaos-Full-Cover-I](https://github.com/overbound/SonicTimeTwisted2.0/assets/141451277/ecb125de-150b-44da-9f46-715a911bc76d)
![Sonic-Chaos-Full-Cover-II](https://github.com/overbound/SonicTimeTwisted2.0/assets/141451277/335ff64a-270a-4dc1-88a4-5ad4d9675301)

**Comment by BlueSpeedsterYT** [comment]
That would break the game's balance as a whole so it's best we don't add those unless we make a remake of the game
