### ISSUE TITLE
Sonic Boost

### ISSUE THREAD

**Issue by KrabbyCurse** [overbound/SonicTimeTwisted2.0#70]
We need Sonic Boost for Sonic
https://sonic.fandom.com/wiki/Boost

**Comment by jtn00b** [comment]
Sure, let's turn the entire game into a Modern Sonic game while we're at it.

Jokes aside, Sonic isn't meant to have the boost in this game, nor it would be fitting anyway. It also would require to revisit every single level as they were not designed with the boost in mind.
