### ISSUE TITLE
Additional Options

### ISSUE THREAD

**Issue by DrEggyniks91** [overbound/SonicTimeTwisted2.0#73]
Video (Screen) Options:
Screen Ratio: 4:3/16:9
Screen Showcase(?): Emulator, Hardware, Original, Scanlines and others things from S1 Forever.
HUD: Classic (Time: 0:00), Mania (0,00,00)

Sound Options:
OST: Original and Remixed and (probably add Sega Cd Ost???)
Sound Test
Special Stage Jingle: Custom and OG

Extra:
Rotation: Classic and 360°
Time Travel: (its up to you)
Lives System: Classic, Mobile and Custom (depends on what device you use or your placement)
Controller: D Pad, OG and Sega Cd-Esque
Super Form: Chrono only, Super only, Chrono and Super.
Easter Eggs: Activated, Deactivate.
etc.

**Comment by overbound** [comment]
This is about 12 separate requests.
