### ISSUE TITLE
Expanded “Post Game” - Record Attack, Boss Rush, and Extra Challenges! 

### ISSUE THREAD

**Issue by ChronoSariel** [overbound/SonicTimeTwisted2.0#77]
This pitches the ideas of including features found some of the rereleases of the classic Sonic games and Mania, particularly the Record Attack, Competition Mode, Boss Rush, and Achievements.

*Record Attack: Works as your bog standard speed run mode, with the extra option of playing the whole game with a speed run timer “marathon mode,” if you wanted to get fancy perhaps adding a replay function that lets you record inputs and send them as files for other people akin to how demos work in DooM.

*Boss Rush: Truncates the record attack to just being a stage with all the bosses fought in order, includes a “no hit mode” that removes rings and shields from the stage. Also includes the replay functionality if it is added.

*Competition Mode: Play truncated versions of existing stages with another player, this utilizes split screen very similar to the Genesis games. Comes in two extra modes “battle” and “race.”
                -Battle: Each player starts with three lives and the goal is to kill the other, the game end when either player runs out of lives or the timer reaches its limit, when this happens both players are put into sudden death, this makes it that they only have one life and zero rings.
                -Race: The name is self explanatory, it works like the Race mode in Sonic Mania.

*Achievements: Don’t have much to say bout it but perhaps it could do the S3 AIR thing where getting a certain amount unlocks things like Debug mode.

![7A7D2BA8-28F1-4F90-80F6-38171A7DEE1C](https://github.com/overbound/SonicTimeTwisted2.0/assets/86979628/8ee28054-d496-4cf5-8509-1b42c7a5d9c4)

**Comment by overbound** [comment]
There would need to be submitted as separate  issues and some of them are duplicates of stuff we already have. Anything 2 player is unlikely ATM.
