### ISSUE TITLE
Potential Overhaul of the Pause Menu in a Stage

### ISSUE THREAD

**Issue by BlueSpeedsterYT** [overbound/SonicTimeTwisted2.0#79]
This aims at looking to change the pause menu design for 2.0.
The following example shown is of Sonic Legends (the Chao Games Showcase build)
![image](https://github.com/overbound/SonicTimeTwisted2.0/assets/36098277/500e17c0-8870-4dbd-9906-c4c5e329b732)
This could be a point on how the pause menu can be improved, as the Chaos Emerald/Time Stones counter could be shown up top, with the pause menu design not looking like the rest of the game's menu designs. That could help with how the game can improve it's look for 2.0, (alongside making sure that it all stays the same in 4:3)

**Comment by overbound** [comment]
I really prefer the UI we have.
