### ISSUE TITLE
Potential Overhaul of the Options Menu in a Stage

### ISSUE THREAD

**Issue by BlueSpeedsterYT** [overbound/SonicTimeTwisted2.0#80]
This aims at potentially improving the option menu design in 2.0 while the game is paused.
The following example is from the Harinezumi Framework
![image](https://github.com/overbound/SonicTimeTwisted2.0/assets/36098277/74c60b8b-3f78-4514-ac73-516dae55ee97)
This should help influence a potential way to make the options menu look different during a stage rather than in the title screen. This can also help with masking the aspect ratio change should Pull Request #50 get merged into the main repo. Of course, this may not be the final design but it could help on making the menus look different in-game

**Comment by overbound** [comment]
A lot of people like the simple UI we have. It gets out of the way and doesn't over stay its welcome. Don't think we'll do this one.
